---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangman.
--- DateTime: 2021/7/20 16:39
---

---@class APoint2
---@field x number
---@field y number
local APoint2 = Class("Point2")

function APoint2:ctor(x, y)
    self.x = x
    self.y = y
end 

function APoint2:ToString()
    return "(x == " .. x .. " y == " .. y .. ")"
end

---Distance2
---@param p APoint2
function APoint2:Distance2(p)
    local dx = p.x - self.x
    local dy = p.y - self.y
    return dx * dx + dy * dy
end

function APoint2.CreateKey(x, y)
    return x + y * 65536
end

---Equals
---@param p APoint2
function APoint2:Equals(p)
    if p == nil then
        return false
    end
    
    return p.x == self.x and p.y == self.y
end

return APoint2

