---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangman.
--- DateTime: 2021/8/3 15:10
---

---@class AMapDataType
---@field Normal number
---@field SlowDown number
---@field Block number
AMapDataType = {}
AMapDataType.Normal = 0
AMapDataType.Block = 1
AMapDataType.SlowDown = 2

---@class AMapDataBase
---@field blockData number[][]
---@field mapWidth number
---@field mapHeight number
local AMapDataBase = Class("AMapDataBase")

function AMapDataBase:ctor(mapWidth, mapHeight)
    self.mapWidth = mapWidth or 1400
    self.mapHeight = mapHeight or 1400
    self.blockData = self.blockData or {}
end

function AMapDataBase:SetMapSize(mapWidth, mapHeight)
    self.mapWidth = mapWidth or 1400
    self.mapHeight = mapHeight or 1400
end

---GetMapDataType
---@param x number
---@param y number
---@return AMapDataType
function AMapDataBase:GetMapDataType(x, y)
    if x > self.mapWidth - 1 or x < 0 or y > self.mapHeight - 1 or y < 0 then
        return AMapDataType.Block
    elseif self.blockData[x] ~= nil and self.blockData[x][y] ~= nil then
        return AMapDataType.Block
    else
        return AMapDataType.Normal
    end
end

function AMapDataBase:IsBlock(x, y)
    if x > self.mapWidth - 1 or x < 0 or y > self.mapHeight - 1 or y < 0 then
        return true
    else
        return self.blockData[x] ~= nil and self.blockData[x][y] ~= nil
    end
end

function AMapDataBase:SetBlock(x, y)
    if x > self.mapWidth - 1 or x < 0 or y > self.mapHeight - 1 or y < 0 then
        PrintError("in AMapData SetBlock out bounds Error x == " .. x .. " y == " .. y)
        return
    end
    self.blockData[x] = self.blockData[x] or {}
    self.blockData[x][y] = AMapDataType.Block
end

function AMapDataBase:ClearBlock()
    self.blockData = {}
end

return AMapDataBase