---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangman.
--- DateTime: 2021/7/17 12:09
---

---@class ANodePool
---@field size number
---@field head ANode
local ANodePool = Class("ANodePool")

local ANode = require("Game.Base.Astar.ANode")

function ANodePool:ctor()
    self.size = 0
    self.head = nil
end

---GetFreeNode
---@return ANode
function ANodePool:GetFreeNode()
    if self.size == 0 then
        return ANode.New()
    elseif self.size == 1 then
        self.size = 0
        return self.head
    else
        ---@type ANode
        local aNode = self.head
        self.head = self.head.Next
        aNode.Next = nil
        self.size = self.size - 1
        return aNode
    end
end

---PushFreeNodeToPool
---@param node ANode
function ANodePool:PushFreeNodeToPool(node)
    node:Reset()
    if self.size == 0 then
        self.head = node
    else
        node.Next = self.head
        self.head = node
    end

    self.size = self.size + 1
end

function ANodePool:CacheNode(count)
    for i = 1, count do
        self:PushFreeNodeToPool(ANode.New())
    end
end

---@type ANodePool
ANodePoolManager = ANodePool.New()
