---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lihaixu.
--- DateTime: 2021/8/16 16:56
---

---@class CityMapData:AMapDataBase
---@field blockData number[][]
---@field mapWidth number
---@field mapHeight number
local CityMapData = Class("AMapData", require("Game.Base.Astar.AMapDataBase"))

function CityMapData:SetBlockInfo(block_info)
    self:ClearBlock()
    for i, v in ipairs(block_info) do
        self:SetBlock(v.x, v.y)
    end    
end

function CityMapData:ctor(mapWidth, mapHeight)
    self.super:ctor(mapWidth, mapHeight)
end

return CityMapData
