---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bing Lau.
--- DateTime: 2021/8/11 18:03
---
---

Mathf = require "Lib.UnityEngine.Mathf"
Vector3 = require "Lib.UnityEngine.Vector3"
Quaternion = require "Lib.UnityEngine.Quaternion"
Vector2 = require "Lib.UnityEngine.Vector2"
Vector4 = require "Lib.UnityEngine.Vector4"
Color = require "Lib.UnityEngine.Color"
Ray = require "Lib.UnityEngine.Ray"
Bounds = require "Lib.UnityEngine.Bounds"
RaycastHit = require "Lib.UnityEngine.RaycastHit"
LayerMask = require "Lib.UnityEngine.LayerMask"
Plane = require "Lib.UnityEngine.Plane"
--Time = reimport "Lib.UnityEngine.Time"